blank_issues_enabled: false
contact_links:
  - name: Report a vulnerability
    url: https://github.com/josunefoOrg/golden-repo/blob/main/SECURITY.md
    about: Please use SECURITY.md for vulnerability reporting instructions.
